name: Images 
run-name: "Building images 🚀"

on: [push, pull_request]

jobs:          
  build-job:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { model: "rt-ax92u",      sdk: "src-rt-5.02axhnd",      ui: "default",  skip: false }
          - { model: "dsl-ax82u",     sdk: "src-rt-5.02axhnd.675x", ui: "default",  skip: false }
          - { model: "tuf-ax5400",    sdk: "src-rt-5.02axhnd.675x", ui: "default",  skip: false }
          - { model: "tuf-ax3000",    sdk: "src-rt-5.02axhnd.675x", ui: "default",  skip: false }
          - { model: "rt-ax82u",      sdk: "src-rt-5.02axhnd.675x", ui: "default",  skip: false }
          - { model: "rt-ax95q",      sdk: "src-rt-5.02axhnd.675x", ui: "default",  skip: false }
          - { model: "rt-axe95q",     sdk: "src-rt-5.02axhnd.675x", ui: "default",  skip: false }
          - { model: "rt-ax82u_v2",   sdk: "src-rt-5.04axhnd.675x", ui: "default",  skip: false }
          - { model: "rt-ax5400",     sdk: "src-rt-5.04axhnd.675x", ui: "default",  skip: false }
          - { model: "tuf-ax3000_v2", sdk: "src-rt-5.04axhnd.675x", ui: "default",  skip: false }
          - { model: "rt-ax58u_v2",   sdk: "src-rt-5.04axhnd.675x", ui: "default",  skip: false }

    container:
      image: gnuton/asuswrt-merlin-toolchains-docker:latest
      env:
        MERLINUPDATE: "y"
        MODEL: ${{ matrix.cfg.model }}
        SDK: ${{ matrix.cfg.sdk }}
        UI: ${{ matrix.cfg.ui }}
        SKIP_BUILD: ${{ matrix.cfg.skip }}
        GIT_REPO: "https://github.com/gnuton/asuswrt-merlin.ng.git"
        PROJECT_DIR: "/project/asuswrt-merlin.ng"
        ARTIFACTS_DIR: "/project/artifacts"
        CHANGELOG_FILE: "/tmp/CHANGELOG"
        PROJECTBASEDIR: "/project"
      options: --user docker 
      volumes:
        - /mnt:/project

    steps:

      - name: Debug disk
        run: |
          cd /
          df -h

      - name: Fix permissions
        if: matrix.cfg.skip == false
        run: |
          sudo chown -R docker:docker /github/home /home/docker /project

      - name: Install build deps (fix autotools hell)
        if: matrix.cfg.skip == false
        run: |
          echo "----- Installing autotools deps -----"
          sudo apt-get update
          sudo apt-get install -y \
            libtool \
            libtool-bin \
            autoconf \
            automake \
            pkg-config

          export ACLOCAL_PATH=/usr/share/aclocal

          echo "----- Versions -----"
          autoconf --version || true
          automake --version || true
          libtoolize --version || true

      - name: Fetch code
        if: matrix.cfg.skip == false
        run: |
          cd /project

          if [[ $SKIP_BUILD == "true" ]]; then
            echo "Skipping build!"
            exit 0
          fi

          if [[ $GITHUB_REF_TYPE == "tag" ]]; then
              TAG="${GITHUB_REF#refs/tags/}"
              echo "Fetching tag $TAG"
          else
              BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
              echo "Fetching branch $BRANCH"
          fi

          git clone --depth 1 --branch "${TAG:-$BRANCH}" "$GIT_REPO"

      - name: Set version
        if: matrix.cfg.skip == false
        run: |
          cd ${PROJECT_DIR}

          CIRCLE_TAG="${GITHUB_REF#refs/*/}"

          if [[ $GITHUB_REF_TYPE != "branch" ]]; then
              TAG=$(echo ${CIRCLE_TAG} | sed 's/^[^.]*\.//')
              MAJOR_VER=$(echo "${TAG}" | sed -E 's/([0-9.]*)[_-]?(.*)/\1/')
              MINOR_VER=$(echo "${TAG}" | sed -E 's/([0-9.]*)[_-]?(.*)/\2/')

              sed -i "s/SERIALNO=.*/SERIALNO=${MAJOR_VER}/g" release/src-rt/version.conf
              sed -i "s/EXTENDNO=.*/EXTENDNO=${MINOR_VER}/g" release/src-rt/version.conf
          fi

      - name: Generate changelog
        if: matrix.cfg.skip == false
        run: |
          cd ${PROJECT_DIR}
          python tools/get-last-notes.py > "${CHANGELOG_FILE}"

      - name: Build
        if: matrix.cfg.skip == false
        run: |
          echo "----- Build start -----"
          cd ${PROJECT_DIR}/release/${SDK}

          if [[ ${SDK} == "src-rt-5.04axhnd.675x" ]]; then
            source /home/docker/envs/bcm-hnd-ax-4.19.sh
          else
            source /home/docker/envs/bcm-hnd.sh
          fi

          sudo ln -sf /home/docker/am-toolchains/brcm-arm-hnd /opt/toolchains

          export ACLOCAL_PATH=/usr/share/aclocal

          echo "----- Running make ${MODEL} -----"
          make "${MODEL}"

      - name: Prepare artifacts
        if: matrix.cfg.skip == false
        run: |
          mkdir -p "${ARTIFACTS_DIR}"

          IMAGE_PATH=${PROJECT_DIR}/release/${SDK}/image/
          rm -rf ${IMAGE_PATH}/*cferom*

          for f in ${IMAGE_PATH}/*; do
            if [[ -f "$f" && "$f" != *.md5 ]]; then
              md5sum "$f" > "$f.md5"
              cp "$f" "${ARTIFACTS_DIR}"
              cp "$f.md5" "${ARTIFACTS_DIR}"
            fi
          done

      - name: Upload artifacts
        if: matrix.cfg.skip == false
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.cfg.model }}
          path: /project/artifacts
